name: amd64_windows_gcc

on: [push]

jobs:

  amd64_windows_gcc:
    runs-on: windows-2019
    timeout-minutes: 5
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make
    - run: make
    - name: Get version
      id: version
      run: |
        output=$(build/gfx2next -version)
        echo "::set-output name=result::$output"
    - name: Copy DLL file
      run: |
        cp /usr/bin/msys-2.0.dll build/
    - name: Compress Files
      uses: vimtor/action-zip@v1
      with:
        files: README.md build/gfx2next.exe build/msys-2.0.dll
        dest: build/gfx2next_Windows_amd64.zip
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/gfx2next_Windows_amd64.zip
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/gfx2next_Windows_amd64.zip
        tag: ${{ steps.version.outputs.result }}
        overwrite: true
